name: hp-tuning

on:
  pull_request:
    branches: main

permissions: write-all

jobs:
  hp_tune_and_publish_report:
    if: startsWith(github.head_ref, 'hp_tune/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Setup DVC
        uses: iterative/setup-dvc@v1

      - name: Setup CML
        uses: iterative/setup-cml@v1

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run DVC pipeline
        run: |
          curl https://assets.datacamp.com/production/repositories/6313/datasets/23f9a730997791402d0ce59bcb7d4007ddfeb540/weather.csv -o raw_dataset/weather.csv
          dvc repro -f hp_tune
      
      - name: Create training branch
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml comment create hp_tuning_results.md
          export BRANCH_NAME=train/$(git rev-parse --short "${{ github.sha }}")
          cml pr create --user-email hp-bot@cicd.ai --user-name HPBot --message "HP tuning" --branch $BRANCH_NAME --target-branch main rfc_best_params.json
